import './globals.scss'
import Link from "next/link";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    return (
        <html lang="en">
        <body>
        <div className='flex w-screen h-screen bg-[#22202F] relative top-0'>
            <div className="relative z-10 w-full h-full">
                {/*navbar*/}
                <Navbar/>


                {children}

                <Footer/>
            </div>
            <div className='absolute rounded-full h-[720px] w-[720px] bg-white z-0' style={{
                background: 'radial-gradient(50% 50% at 50% 50%, rgba(182, 22, 166, 0.2) 0%, rgba(234, 0, 213, 0) 100%)',
                bottom: '-150px',
                right: '-150px'
            }}/>
            <div className='absolute rounded-full h-[720px] w-[720px] bg-white z-0' style={{
                background: 'radial-gradient(50% 50% at 50% 50%, rgba(209, 114, 200, 0.2) 0%, rgba(234, 0, 213, 0) 100%)',
                transform: 'translate(-50%, -20%)',
                left: '50%'
            }}/>
            <div className='absolute rounded-full h-[720px] w-[720px] bg-white z-0' style={{
                background: 'radial-gradient(50% 50% at 50% 50%, rgba(112, 119, 229, 0.5) 0%, rgba(112, 119, 229, 0) 100%)',
                transform: 'translate(-20%, 30%)'
            }}/>
        </div>
        </body>
        </html>
    )
}
